### ISSUE TITLE
Problem with encrypted phone / unable to decrypt phonencryption

### ISSUE THREAD

**Issue by thrdroom** [TeamWin/android_device_bq_piccolometal#1]
### Problem/Bug:

When i encrypt my X5 CyanogenOS i cannot longer use TWRP to backup, flash etc.
TWRP is asking for the password to decrypt, but even with the right password TWRP is unable to decrypt the data.
### Error Message in TWRP:

```
Updating partition details...
...done
Unable to mount storage
Full SELinux support is present.
Failed to decrypt data.
```
### Steps to reproduce:
1. Flash clean CyaogenOS image ([cm-12.1-YOG4PAS9OI-paella-signed-fastboot-08a5c4b830.zip](http://builds.cyngn.com/factory/paella/cm-12.1-YOG4PAS9OI-paella-signed-fastboot-08a5c4b830.zip))
2. Flash newest TWRP image ([twrp-3.0.2-1-piccolometal.img](https://dl.twrp.me/piccolometal/twrp-3.0.2-1-piccolometal.img))
3. Set a password for the lockscreen
4. Settings app -> Security -> Encrypt phone
5. Boot in TWRP -> TWRP tries to mount the data-partition -> Enter password

**Comment by Kra1o5** [comment]
Hi @thrdroom ,

Is a know issue, already fixed here: https://github.com/TeamWin/android_device_bq_piccolometal/commit/838b8934b4816cdb0a15710067712990f64a4964

It will be included in next twrp release.

Regards

**Comment by thrdroom** [comment]
Thanks for your reply @Kra1o5 

Thats awesome! Can you give me an ETA for this release cause this problem bugs me for months now and i cant do any critical testing like e.g. CM13-nightlys witout a full-system backup.

Last update is nearly 5 months old.

Regards

**Comment by Kra1o5** [comment]
I will try to get new update asap.

Greetings

**Comment by thrdroom** [comment]
@Kra1o5 What about the Updates? Can we have them plz? :)

**Comment by Kra1o5** [comment]
Hi @thrdroom,

Sorry Im busy, but I try to make it available this week.

**Comment by thrdroom** [comment]
![45f](https://cloud.githubusercontent.com/assets/5912061/20477668/f43f3c44-afd6-11e6-89f1-50b5f6c247f7.jpg)

@Kra1o5 
Maybe find a comaintainer?

**Comment by Kra1o5** [comment]
Hi @thrdroom ,

Really sorry for the delay.

You can get it here: https://dl.twrp.me/piccolometal/

Greetings

**Comment by thrdroom** [comment]
@Kra1o5 THX for the Update 👍 But the problem persists even with "twrp-3.0.2-2" :(

`Failed to decrypt data.`

Can you please fix this issue? Ive been waiting for so long :/

**Comment by eloimuns** [comment]
Probably only work with stock X5.

**Comment by thrdroom** [comment]
Do have the stock-rom Installed? Can you test this @eloimuns ?

**Comment by thrdroom** [comment]
Problem does **not** persist with CyangenOS 13. But is still present with CyangenOS 12.1, which is kinda annoying as it makes updating an encrypted device without a full wipe impossible.

**Comment by Kra1o5** [comment]
Oh, yes

The fix affect 13.1

**Comment by frere-jacques** [comment]
I have the same problem.
At Moment with the I think early March LineageOS build and with newest TWRP.
It would be perfect if it would work.

**Comment by LineageOS-User** [comment]
same problem at TWRP 3.1.0-0 and actually LineageOS_14.1 nightly_build (03-23).
TWRP is unable to mount encrypted phone, the right password will not accepted.

So at the moment I can´t install updates and making backups.

**Comment by LineageOS-User** [comment]
No one who can take care of this issue?

**Comment by Kra1o5** [comment]
If you use stock firmware as base will not have any issue with encryption and since CyanogenOS not exist anymore is the best idea.

Greetings

**Comment by frere-jacques** [comment]
Sorry I don't get this.  What do you mean with standard firmware? Do you mean the factory default Android? But I am using TWRP to run LineageOS and in the moment I am desperately waiting that I can backup my encrypted device und update it again.

Best
8FordPrefect8

**Comment by stucki** [comment]
Download the stock firmware from https://www.bq.com/en/support/aquaris-x5/support-sheet and flash these files. It will replace all your data, so make a backup.

Alternatively, edit the included script and skip flashing of system, userdata etc.

Once this is flashed, you can install TWRP and LineageOS again and as usual...

**Comment by frere-jacques** [comment]
Thank you very much. Indeed it worked, although it was a time consuming task.

**Comment by stucki** [comment]
Issue can be closed. @8FordPrefect8 thanks for your feedback!
